# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

search:
  namespace: "pyvespa-p"
  doc_type: "paragraph"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.z.vespa-app.cloud/
      indexes:
        - paragraph_index.json 
    - url: https://vespacloud-docsearch.vespa-team.gcp-us-central1-f.z.vespa-app.cloud/
      indexes:
        - paragraph_index.json 
    - url: https://vespacloud-docsearch.vespa-team.aws-eu-west-1a.z.vespa-app.cloud/
      indexes:
        - paragraph_index.json 
    # vespacloud-docsearch.cloud-enclave
    # prod.aws-us-east-1c
    - url: https://c967e4f5.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - paragraph_index.json
    # vespacloud-docsearch.cloud-enclave
    # prod.gcp-us-central1-f
    - url: https://ab1f72fd.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - paragraph_index.json
