name: Integration - except cloud

on:
  workflow_dispatch:
  push:
    branches:
      - glebashnik/integration-except-cloud-to-github-action
  # Uncomment it when reviewed
  #   - master
  # pull_request:
  #   branches:
  #     - master
  # schedule:
  #  - cron: '0 11 * * *'

jobs:
  integration-except-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            **/notebook_requirements.txt
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Run integration docker
        run: |
          pytest tests/integration/test_integration_docker.py -s -v
