name: Integration - cloud

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths: [".github/workflows/integration-cloud.yml"]
  schedule:
    - cron: "0 11 * * 0"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  integration-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.10"
          cache: "pip"
      - run: echo '${{ steps.setup-python.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
      - name: Install dependencies
        run: |
          pip install -e .[dev]

      - name: Run integration tests
        env:
          VESPA_TEAM_API_KEY: ${{ secrets.VESPA_TEAM_API_KEY }}
        run: |
          pytest tests/integration/test_integration_vespa_cloud.py -s -v

  integration-cloud-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.10"
          cache: "pip"
      - run: echo '${{ steps.setup-python.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
      - name: Install dependencies
        run: |
          pip install -e .[dev]

      - name: Run integration tests
        env:
          VESPA_TEAM_API_KEY: ${{ secrets.VESPA_TEAM_API_KEY }}
          VESPA_CLOUD_SECRET_TOKEN: ${{ secrets.VESPA_CLOUD_SECRET_TOKEN }}
          VESPA_CLIENT_TOKEN_ID: ${{ secrets.VESPA_CLIENT_TOKEN_ID }}
        run: |
          pytest tests/integration/test_integration_vespa_cloud_token.py -s -v

  integration-cloud-vector-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: echo '${{ steps.setup-python.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
      - name: Install dependencies
        run: |
          pip install -e .[dev]

      - name: Run integration tests
        env:
          VESPA_TEAM_API_KEY: ${{ secrets.VESPA_TEAM_API_KEY }}
        run: |
          pytest tests/integration/test_integration_vespa_cloud_vector_search.py -s -v
