name: Integration - cloud token

on:
  workflow_dispatch:
  push:
    branches:
      - glebashnik/integration-cloud-to-github-action
  # Uncomment it when reviewed
  #   - master
  # pull_request:
  #   branches:
  #     - master
  # schedule:
  #  - cron: '0 11 * * *'

jobs:
  integration-cloud-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Run integration tests
        env:
          VESPA_TEAM_API_KEY: ${{ secrets.VESPA_TEAM_API_KEY }}
          CO_API_KEY: ${{ secrets.VESPA_CLOUD_SECRET_TOKEN }}
          SD_ZIP_ARTIFACTS: true
        run: |
          pytest tests/integration/test_integration_vespa_cloud_token.py -s -v
