name: Integration - cloud

on:
  workflow_dispatch:
  push:
    branches:
      # Replace this with master when reviewed.
      - glebashnik/integration-cloud-to-github-action

jobs:
  integration-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Run integration tests
        env:
          VESPA_TEAM_API_KEY: ${{ secrets.VESPA_TEAM_API_KEY }}
          CO_API_KEY: ${{ secrets.CO_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/integration/test_integration_vespa_cloud.py -s -v
