name: MKDocs test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  mk-docs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: |
          sudo apt-get install -y pandoc
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --extra dev --extra docs
      - name: Run tests
        run: |
          uv run pytest tests/mktestdocs -s -v
      - name: Build docs
        run: |
          uv run mkdocs build --site-dir docs/sphinx/build
      - name: Run linkcheck
        run: |
          uv run .github/scripts/linkcheck.py --ignore-url-file .github/scripts/ignore_urls.txt docs/sphinx/source/
