name: MKDocs test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  mk-docs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          pip install -e .[docs]
      - name: Run tests
        run: |
          pytest tests/mktestdocs -s -v

      - name: Linkcheck
        run: |
          mkdocs-linkcheck docs/sphinx/source/
