name: Notebooks except cloud

on:
  workflow_dispatch:
  push:
    branches:
      - glebashnik/integration-except-cloud-to-github-action
  # Uncomment it when reviewed
  #   - master
  # pull_request:
  #   branches:
  #     - master
  # schedule:
  #  - cron: '0 11 * * *'

jobs:
  get-non-cloud-notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.set_output.outputs.notebooks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set output variable (Make sure it is this quote format - "[path/to/notebook1.ipynb", "path/to/notebook2.ipynb]")
        id: set_output
        run: |
          notebooks=$(find docs -name '*.ipynb' ! -name '*cloud*.ipynb' ! -name 'colpali-document-retrieval-vision-language-models.ipynb' | jq -R -s -c 'split("\n")[:-1]')
          # Print all notebooks echo
          echo $notebooks
          echo "notebooks=$notebooks" >> $GITHUB_OUTPUT

  notebooks-except-cloud:
    runs-on: ubuntu-latest
    needs: get-non-cloud-notebooks
    strategy:
      max-parallel: 8
      matrix:
        notebook: ${{fromJson(needs.get-non-cloud-notebooks.outputs.notebooks)}}
    steps:
      - uses: actions/checkout@v4

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            **/notebook_requirements.txt

      - name: Install dependencies
        run: |
          pip install -e .[dev]
          pip install -r docs/sphinx/source/notebook_requirements.txt

      - name: Install OpenMP
        run: |
          # Required for using lightgbm
          sudo apt install -y install libgomp1 zstd

      - name: Run notebooks tests
        run: |
          echo "Running ${{ matrix.notebook }}"
          jupytext --to py:percent ${{ matrix.notebook }} -o ${{ matrix.notebook }}.py
          echo "Running ${{ matrix.notebook }}.py"
          python ${{ matrix.notebook }}.py
