name: Notebooks - cloud

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 11 * * 0"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  get-notebooks-cloud:
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.set_output.outputs.notebooks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set output variable (Make sure it is this quote format - "[path/to/notebook1.ipynb", "path/to/notebook2.ipynb]")
        id: set_output
        run: |
          notebooks=$(find docs/sphinx/source -name '*cloud.ipynb' ! -name 'mother-of-all-embedding-models-cloud.ipynb' ! -name 'scaling-personal-ai-assistants-with-streaming-mode-cloud.ipynb' | jq -R -s -c 'split("\n")[:-1]')
          # Print all notebooks echo
          echo $notebooks
          echo "notebooks=$notebooks" >> $GITHUB_OUTPUT

  notebooks-cloud:
    runs-on: ubuntu-latest
    needs: get-notebooks-cloud
    strategy:
      matrix:
        notebook: ${{fromJson(needs.get-notebooks-cloud.outputs.notebooks)}}

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up uv
        # Install a specific uv version using the installer
        run: curl -LsSf https://astral.sh/uv/0.4.5/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync --extra dev --extra notebooks

      - name: Run notebooks tests
        env:
          VESPA_TEAM_API_KEY: ${{ secrets.VESPA_TEAM_API_KEY }}
          VESPA_CLOUD_SECRET_TOKEN: ${{ secrets.VESPA_CLOUD_SECRET_TOKEN }}
          CO_API_KEY: ${{ secrets.CO_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UV_SYSTEM_PYTHON: 1
        run: |
          echo "Running ${{ matrix.notebook }}"

          # Function to extract, modify and save the pip install command
          function process_pip_installation {
            # 1. Extract lines that start with '!pip[3] install [optional -U] package1 package2 ...'
            # 2. Remove the leading "!" and strip 'pyvespa' and 'vespacli'
            # 3. Write the result to additional_requirements.txt and prefix the original line with "#" in the notebook

            # Extract all pip install lines and loop through them
            grep -E '^!pip(3)? install( -U)? ' $1 | while read -r line ; do
              # Strip the leading "!"
              modified_line=$(echo "$line" | sed 's/^!//')
              
              # Remove 'pyvespa' and 'vespacli' from the line
              modified_line=$(echo "$modified_line" | sed 's/pyvespa//g' | sed 's/vespacli//g' | sed 's/  / /g')

              # 4. Write the result to additional_requirements.txt
              echo "$modified_line" >> additional_requirements.txt
              
              # Echo the modified command
              echo "Modified command: $modified_line"

              # 5. Comment out the original line in the notebook by prefixing it with '#'
              sed -i '' "s|$line|# $line|g" $1
            done
          }

          # Call the function to process pip install lines and modify the notebook
          process_pip_installation "${{ matrix.notebook }}"

          # Install additional requirements with uv
          uv pip install -r additional_requirements.txt

          # Run the modified notebook
          papermill --log-output ${{ matrix.notebook }} ${{ matrix.notebook }}-out.ipynb
