name: pyvespa - Bump version

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Bump version
        run: |
          pip install -e .[build]
          bump-my-version bump patch -v

     