name: pyvespa - Release and upload PyPI

on:
  workflow_dispatch:
  # release: Disable auto-release until actions are approved
  #   types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]

      - name: Set version from ref tag that triggered the workflow (strip prefix 'v' from tag)
        id: set_version
        run: |
          echo "GITHUB_REF=$GITHUB_REF" 
          # strip prefix 'v' from version variable
          version=${GITHUB_REF#refs/tags/v}
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update version
        run: |
          echo "Updating pyvespa version to ${{ steps.set_version.outputs.version }}"
          python vespa/utils/update_version.py --version ${{ steps.set_version.outputs.version }}

      - name: Build
        run: |
          python -m build

      - name: Upload to PyPI
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_PYVESPA }} #TODO: this must be added to secrets
        run: python -m twine upload dist/*

      - name: Commit and PR
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_BRANCH:  "update-pyvespa-version-${{ steps.set_version.outputs.version }}"
        run: |
          git checkout -b "${NEW_BRANCH}"
          git commit -a -m "Update pyvespa version to ${{ steps.set_version.outputs.version }}"
          git push --set-upstream origin "${NEW_BRANCH}"
          gh pr create -B master -H "${NEW_BRANCH}" \
            -t "Update pyvespa version to ${{ steps.set_version.outputs.version }}" \
            -b "This PR updates the pyvespa version to ${{ steps.set_version.outputs.version }}" 

